---
services:
  dns-manager-db:
    image: docker.io/library/postgres:18
    container_name: dns-manager-db
    restart: always
    environment:
      POSTGRES_USER: dnsmanager
      POSTGRES_PASSWORD: dnsmanager
      POSTGRES_DB: dnsmanager
    volumes:
      - dns_manager_db_data:/var/lib/postgresql

  dns-manager-app:
    image: ghcr.io/annttu/dns-manager:latest
    container_name: dns-manager-app
    restart: on-failure
    depends_on:
      - dns-manager-db
    environment:
      DATABASE_HOST: dns-manager-db
      DATABASE_PORT: 5432
      DATABASE_NAME: dnsmanager
      DATABASE_USER: dnsmanager
      DATABASE_PASSWORD: dnsmanager
      ALLOWED_HOSTS: localhost,example.com
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  dns_manager_db_data:
