# Generated by Django 5.2.15 on 2026-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_auto_20151210_1948"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dnsentrycache",
            options={"ordering": ["name", "type"]},
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dnsentrycache",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="dnsentrycache",
            name="record_class",
            field=models.CharField(default="IN", max_length=128),
        ),
        migrations.AlterField(
            model_name="dnsentrycache",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dnsentrycache",
            name="ttl",
            field=models.IntegerField(default=360),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("domain", "name"), name="unique_domain_name"
            ),
        ),
    ]
